name: 'Deploy site'

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yml
      - .github/workflows/deploy.yml
      - src/**/*
      - types/**/*
      - yarn.lock

jobs:
  build:
    name: 'Build site'
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      upload: true

  deploy:
    name: 'Deploy to GitHub pages'
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: build
          path: developer

      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: developer
          token: ${{ secrets.GH_REPO_TOKEN }}

      - uses: reggionick/s3-deploy@v3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
          bucket: ${{ secrets.S3_BUCKET }}
          delete-removed: true
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          folder: developer
          private: true
