name: 'Check pull request'

on: pull_request

jobs:
  build:
    name: 'Test site build'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - uses: ./.github/workflows/build
