name: 'Push to main 🚀'

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploy to GHP and AWS'
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - uses: myparcelnl/actions/setup-app-credentials@v3
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: ./.github/actions/build

      - uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: src/.vuepress/dist
          token: ${{ steps.credentials.outputs.token }}

      - uses: reggionick/s3-deploy@v3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
          bucket: ${{ secrets.S3_BUCKET }}
          delete-removed: true
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          folder: src/.vuepress/dist
          private: true

  rebase-prs:
    name: 'Rebase open pull requests'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: myparcelnl/actions/setup-app-credentials@v3
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: peter-evans/rebase@v2
        with:
          token: ${{ steps.credentials.outputs.token }}
