name: 'Push to main 🚀'

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - uses: ./.github/actions/build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: src/.vuepress/dist

      - uses: reggionick/s3-deploy@v3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
          bucket: ${{ secrets.S3_BUCKET }}
          delete-removed: true
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          folder: src/.vuepress/dist
          private: true

  deploy:
    needs: upload
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1

  rebase-prs:
    name: 'Rebase open pull requests'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: myparcelnl/actions/setup-app-credentials@v3
        id: credentials
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}

      - uses: peter-evans/rebase@v2
        with:
          token: ${{ steps.credentials.outputs.token }}
